resources
| where type == "microsoft.logic/workflows"
| where isnotnull(properties.definition.triggers.manual.kind)
| join kind=inner (
    resourcecontainers
    | where type == 'microsoft.resources/subscriptions'
    | project subscriptionId, subscriptionName = name)
    on subscriptionId
| project name, resourceGroup, subscriptionName, subscriptionId, state=properties.state, triggerType=properties.definition.triggers.manual.kind, triggerUri=todynamic(properties)['accessEndpoint'], properties
