resources
| where type == "microsoft.web/connections" and properties.parameterValues.["token:clientId"] != ''
| extend Props=todynamic(properties)
| project Id=id, Name=name, ResourceGroup=resourceGroup, SubscriptionId=subscriptionId, DisplayName=Props["displayName"], State=Props["connectionState"], Status=Props["overallStatus"], ApiType=Props["api"]["name"], ClientId=Props["parameterValues"]["token:clientId"], ParameterValues=Props["parameterValues"], StatusDetails=Props["statuses"]
