resources
| where type =~ "microsoft.web/sites"
| join kind=inner (
    resourcecontainers
    | where type == 'microsoft.resources/subscriptions'
    | project subscriptionId, subscriptionName = name)
    on subscriptionId
| join kind=inner (
    resources
    | where type =~ "microsoft.web/sites"
    | extend sslStates = properties.hostNameSslStates
    | mv-expand sslStates
    | summarize concatenatedNames = strcat_array(make_list(sslStates.name), ", ") by id
    | project id, concatenatedNames
    )
    on id
| project name, resourceGroup, subscriptionName, subscriptionId, kind, State=properties.state, Enabled=properties.enabled, HostNames=concatenatedNames, AppServicePlan=split(properties.serverFarmId, "/")[-1], AppServicePlanId=properties.serverFarmId, id, properties
